### ISSUE TITLE
Will it support Folia?

### ISSUE THREAD

**Issue by pan90** [Cocolennon/TopLuck#1]
https://papermc.io/software/folia

**Comment by Cocolennon** [comment]
Honestly I think it already does, it just doesn't have the folia-support tag in the plugin.yml.
I'll do some tests later

**Comment by Cocolennon** [comment]
I'll start testing this right now, I'll let you know when the plugin is updated for Folia support.

**Comment by Cocolennon** [comment]
Folia is now supported in Top Luck 1.1.0, download available on the Spigot page
