### ISSUE TITLE
GUI is unresponsive and percentages are off

### ISSUE THREAD

**Issue by PtitLegume** [Cocolennon/TopLuck#3]
VERSION : 1.20.5
Top Luck 1.1.1
the gui pop up, but everyone have 9.22...E15% on diamond and nothing happens when i try to click on a head/offline player ( i even can steal the glass plane in my inventory )
![image](https://github.com/Cocolennon/TopLuck/assets/67562086/8917fb92-35cd-4056-b0c3-529a1c2ea236)

**Comment by Cocolennon** [comment]
Hey, sounds like something's being thrown in the console. Can you do these steps for me?

1. Restart server
2. Reproduce the bug
3. Stop the server
4. Grab your latest logs and send them here

Having the logs will help me greatly
Also, if you wish for me to answer faster, please join the [support Discord server](https://discord.gg/yqG4u2JnrV) as I don't get github notifications often

**Comment by Cocolennon** [comment]
Fixed in latest commits
