### ISSUE TITLE
InventoryClickEvent

### ISSUE THREAD

**Issue by Masdestructor** [Cocolennon/TopLuck#4]
Hello,

I have this error in paper 1.20.4 with the latest version of the plugin.

How do you fix the problem?
![Capture d'écran 2024-09-04 190457](https://github.com/user-attachments/assets/952a6dab-dc98-4da5-9dca-5bdb91309d4d)

**Comment by Cocolennon** [comment]
Hey, unfortunately your logs don't provide me with the info I need to fix the problem (the exact line that is throwing the error) so I can't do anything. Is there any way you can get the full error and send it to me?

**Comment by Cocolennon** [comment]
Closing because poster is inactive
